namespace SharpAstrology.Ephemerides.Enums;

public enum SwissEphAyanamsas
{
    FagenBradley = 0,
    Lahiri = 1,
    Deluce = 2,
    Raman = 3,
    Ushashashi = 4,
    Krishnamurti = 5,
    DjwhalKhul = 6,
    Yukteshwar = 7,
    JNBhasin = 8,
    BabylonianKugler1 = 9,
    BabylonianKugler2 = 10,
    BabylonianKugler3 = 11,
    BabylonianHuber = 12,
    BabylonianEtaPiscium = 13,
    BabylonianAldebaran15Tau = 14,
    Hipparchos = 15,
    Sassanian = 16,
    GalacticCenter0Sag = 17,
    J2000 = 18,
    J1900 = 19,
    B1950 = 20,
    Suryasiddhanta = 21,
    SuryasiddhantaMeanSun = 22,
    Aryabhata = 23,
    AryabhataMeanSun = 24,
    SSRevati = 25,
    SSCitra = 26,
    TrueCitra = 27,
    TrueRevati = 28,
    TruePushyaPvrnRao = 29,
    GalacticCenterGilBrand = 30,
    GalacticEquatorIAU1958 = 31,
    GalacticEquator = 32,
    GalacticEquatorMidMula = 33,
    SkydramMardyks = 34,
    TrueMulaChandraHari = 35,
    GalacticCenterMidMula = 36,
    Aryabhata522 = 37,
    BabylonianBritton = 38,
    VedicSheoran = 39,
    CochraneGalCenter0Cap = 40,
    GalacticEquatorFiorenza = 41,
    VettiusValens = 42,
    Lahiri1940 = 43,
    LahiriVP285 = 44,
    KrishnamurtiSenthilathiban = 45,
    LahiriICRC = 46,
    UserDefined = 255
}

